2024-12-09 16:41:23,587 - INFO - Tornado server started on port 8888
2024-12-09 16:41:23,595 - INFO - Subscribed to Redis channel: chat
2024-12-09 16:41:39,747 - INFO - HTTP GET request received on /
2024-12-09 16:41:39,749 - INFO - 200 GET / (::1) 3.00ms
2024-12-09 16:41:39,989 - INFO - 200 GET /static/style.css (::1) 38.62ms
2024-12-09 16:41:39,991 - INFO - 200 GET /static/app.js (::1) 1.00ms
2024-12-09 16:41:40,772 - INFO - 101 GET /ws (::1) 0.99ms
2024-12-09 16:41:40,772 - INFO - New WebSocket connection opened: ::1
2024-12-09 16:41:45,399 - INFO - Received message from ::1: 1234
2024-12-09 16:41:45,403 - INFO - Received message from Redis: 1234
2024-12-09 16:41:45,404 - INFO - Message published to Redis: 1234
2024-12-09 16:41:45,405 - INFO - Message sent to WebSocket client: 1234
2024-12-09 16:41:55,663 - INFO - Received message from ::1: asdgasdgasdgfasdgasd
2024-12-09 16:41:55,665 - INFO - Received message from Redis: asdgasdgasdgfasdgasd
2024-12-09 16:41:55,665 - INFO - Message sent to WebSocket client: asdgasdgasdgfasdgasd
2024-12-09 16:41:55,666 - INFO - Message published to Redis: asdgasdgasdgfasdgasd
2024-12-09 16:43:29,473 - INFO - Server shutdown initiated
2024-12-09 16:43:29,475 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1' coro=<redis_listener() done, defined at c:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\server.py:49> exception=ConnectionError('Connection closed by server.')>
Traceback (most recent call last):
  File "c:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\server.py", line 56, in redis_listener
    async for message in pubsub.listen():
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 1035, in listen
    response = await self.handle_message(await self.parse_response(block=True))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 922, in parse_response
    response = await self._execute(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 902, in _execute
    return await conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\retry.py", line 62, in call_with_retry
    await fail(error)
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 891, in _disconnect_raise_connect
    raise error
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 543, in read_response
    response = await self._parser.read_response(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\_parsers\resp2.py", line 82, in read_response
    response = await self._read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\_parsers\resp2.py", line 90, in _read_response
    raw = await self._readline()
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\_parsers\base.py", line 221, in _readline
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
2024-12-09 16:43:29,481 - INFO - Redis client closed
2024-12-09 16:44:37,163 - INFO - Tornado server started on port 8888
2024-12-09 16:44:41,212 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1' coro=<redis_listener() done, defined at c:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\server.py:49> exception=ConnectionError('Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.')>
Traceback (most recent call last):
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 275, in connect
    await self.retry.call_with_retry(
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 691, in _connect
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1090, in create_connection
    raise exceptions[0]
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 726, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 846, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 633, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] Удаленный компьютер отклонил это сетевое подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\server.py", line 52, in redis_listener
    await pubsub.subscribe("chat")
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 1009, in subscribe
    ret_val = await self.execute_command("SUBSCRIBE", *new_channels.keys())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 858, in execute_command
    await self.connect()
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 868, in connect
    self.connection = await self.connection_pool.get_connection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 1058, in get_connection
    await self.ensure_connection(connection)
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 1091, in ensure_connection
    await connection.connect()
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:44:45,959 - INFO - Server shutdown initiated
2024-12-09 16:44:45,960 - INFO - Redis client closed
2024-12-09 16:44:46,420 - INFO - Tornado server started on port localhost:8888
2024-12-09 16:44:50,503 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1' coro=<redis_listener() done, defined at c:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\server.py:49> exception=ConnectionError('Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.')>
Traceback (most recent call last):
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 275, in connect
    await self.retry.call_with_retry(
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 691, in _connect
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1090, in create_connection
    raise exceptions[0]
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 726, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 846, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 633, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] Удаленный компьютер отклонил это сетевое подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\server.py", line 52, in redis_listener
    await pubsub.subscribe("chat")
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 1009, in subscribe
    ret_val = await self.execute_command("SUBSCRIBE", *new_channels.keys())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 858, in execute_command
    await self.connect()
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 868, in connect
    self.connection = await self.connection_pool.get_connection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 1058, in get_connection
    await self.ensure_connection(connection)
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 1091, in ensure_connection
    await connection.connect()
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:44:58,636 - INFO - HTTP GET request received on /
2024-12-09 16:44:58,639 - INFO - 200 GET / (::1) 2.99ms
2024-12-09 16:44:58,869 - INFO - 101 GET /ws (::1) 1.00ms
2024-12-09 16:44:58,870 - INFO - New WebSocket connection opened: ::1
2024-12-09 16:45:52,413 - INFO - 101 GET /ws (::1) 1.00ms
2024-12-09 16:45:52,414 - INFO - New WebSocket connection opened: ::1
2024-12-09 16:45:54,655 - INFO - Received message from ::1: {"name":"Аноним","message":"asdfasdf"}
2024-12-09 16:45:58,737 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:45:58,738 - INFO - Received message from ::1: {"name":"Аноним","message":"asdf"}
2024-12-09 16:46:02,834 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:02,834 - INFO - Received message from ::1: {"name":"Аноним","message":"asdf"}
2024-12-09 16:46:06,916 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:06,917 - INFO - Received message from ::1: {"name":"1234","message":"asdfasdf"}
2024-12-09 16:46:10,971 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:10,971 - INFO - Received message from ::1: {"name":"1234","message":"asdf"}
2024-12-09 16:46:15,056 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:15,057 - INFO - Received message from ::1: {"name":"1234","message":"asdfasdfasdf"}
2024-12-09 16:46:19,156 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:19,157 - INFO - Received message from ::1: {"name":"1234","message":"asdfasdf"}
2024-12-09 16:46:23,248 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:23,249 - INFO - Received message from ::1: {"name":"1234","message":"asdf"}
2024-12-09 16:46:27,350 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:27,351 - INFO - Received message from ::1: {"name":"1234","message":"asdf"}
2024-12-09 16:46:31,422 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:31,422 - INFO - Received message from ::1: {"name":"1234","message":"asdf"}
2024-12-09 16:46:35,502 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:35,502 - INFO - Received message from ::1: {"name":"1234","message":"asdf"}
2024-12-09 16:46:37,751 - INFO - 101 GET /ws (::1) 1.50ms
2024-12-09 16:46:37,752 - INFO - New WebSocket connection opened: ::1
2024-12-09 16:46:39,596 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:39,597 - INFO - Received message from ::1: {"name":"1234","message":"asdf"}
2024-12-09 16:46:43,672 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:43,672 - INFO - Received message from ::1: {"name":"1234","message":"as"}
2024-12-09 16:46:47,739 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:46:47,740 - INFO - WebSocket connection closed: ::1
2024-12-09 16:46:58,248 - INFO - Received message from ::1: {"name":"Аноним","message":"12341234"}
2024-12-09 16:47:02,361 - ERROR - Failed to publish message to Redis: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:47:35,549 - INFO - WebSocket connection closed: ::1
2024-12-09 16:49:18,026 - INFO - WebSocket connection closed: ::1
2024-12-09 16:50:51,371 - INFO - HTTP GET request received on /
2024-12-09 16:50:51,371 - INFO - 304 GET / (::1) 1.00ms
2024-12-09 16:50:51,443 - INFO - 101 GET /ws (::1) 0.00ms
2024-12-09 16:50:51,444 - INFO - New WebSocket connection opened: ::1
2024-12-09 16:50:52,075 - INFO - HTTP GET request received on /
2024-12-09 16:50:52,076 - INFO - 304 GET / (::1) 1.01ms
2024-12-09 16:50:52,080 - INFO - WebSocket connection closed: ::1
2024-12-09 16:50:52,146 - INFO - 101 GET /ws (::1) 1.00ms
2024-12-09 16:50:52,146 - INFO - New WebSocket connection opened: ::1
2024-12-09 16:50:52,473 - INFO - HTTP GET request received on /
2024-12-09 16:50:52,474 - INFO - 304 GET / (::1) 0.99ms
2024-12-09 16:50:52,478 - INFO - WebSocket connection closed: ::1
2024-12-09 16:50:52,526 - INFO - 101 GET /ws (::1) 1.00ms
2024-12-09 16:50:52,526 - INFO - New WebSocket connection opened: ::1
2024-12-09 16:50:53,939 - INFO - WebSocket connection closed: ::1
2024-12-09 16:51:02,957 - INFO - Server shutdown initiated
2024-12-09 16:51:02,965 - INFO - Redis client closed
2024-12-09 16:51:10,235 - INFO - Tornado server started on port http://localhost:8888
2024-12-09 16:51:11,986 - INFO - HTTP GET request received on /
2024-12-09 16:51:11,988 - INFO - 200 GET / (::1) 2.96ms
2024-12-09 16:51:12,183 - INFO - 101 GET /ws (::1) 1.00ms
2024-12-09 16:51:12,184 - INFO - New WebSocket connection opened: ::1
2024-12-09 16:51:14,293 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1' coro=<redis_listener() done, defined at c:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\server.py:49> exception=ConnectionError('Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.')>
Traceback (most recent call last):
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 275, in connect
    await self.retry.call_with_retry(
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 691, in _connect
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1090, in create_connection
    raise exceptions[0]
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 726, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 846, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 633, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] Удаленный компьютер отклонил это сетевое подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\server.py", line 52, in redis_listener
    await pubsub.subscribe("chat")
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 1009, in subscribe
    ret_val = await self.execute_command("SUBSCRIBE", *new_channels.keys())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 858, in execute_command
    await self.connect()
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\client.py", line 868, in connect
    self.connection = await self.connection_pool.get_connection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 1058, in get_connection
    await self.ensure_connection(connection)
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 1091, in ensure_connection
    await connection.connect()
  File "C:\Users\Prosc\PycharmProjects\OTRPO\lab9_basic_messanger\.venv\Lib\site-packages\redis\asyncio\connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 22 connecting to localhost:6379. Удаленный компьютер отклонил это сетевое подключение.
2024-12-09 16:55:25,102 - INFO - HTTP GET request received on /
2024-12-09 16:55:25,102 - INFO - 304 GET / (::1) 0.99ms
2024-12-09 16:55:25,106 - INFO - WebSocket connection closed: ::1
2024-12-09 16:55:25,159 - INFO - 101 GET /ws (::1) 0.99ms
2024-12-09 16:55:25,159 - INFO - New WebSocket connection opened: ::1
2024-12-09 16:56:15,443 - INFO - Server shutdown initiated
2024-12-09 16:56:15,446 - INFO - Redis client closed
2024-12-10 10:40:23,463 - INFO - Server started on port 8888
2024-12-10 10:40:23,468 - INFO - Redis listener started
2024-12-10 10:42:14,245 - INFO - Server started on port http://localhost:8888
2024-12-10 10:42:14,251 - INFO - Redis listener started
2024-12-10 10:42:16,175 - INFO - 304 GET / (::1) 45.56ms
2024-12-10 10:42:23,200 - INFO - 101 GET /ws?username=%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9 (::1) 1.00ms
2024-12-10 10:42:23,200 - INFO - Active users updated: ['Алексей']
2024-12-10 10:42:23,201 - INFO - User connected: Алексей
2024-12-10 10:42:29,864 - INFO - Message received from Алексей: Привет
2024-12-10 10:42:29,868 - INFO - Redis message received: {"type": "message", "user": "\u0410\u043b\u0435\u043a\u0441\u0435\u0439", "text": "\u041f\u0440\u0438\u0432\u0435\u0442"}
2024-12-10 10:42:33,600 - INFO - 304 GET / (::1) 1.00ms
2024-12-10 10:42:39,416 - INFO - 304 GET / (::1) 1.01ms
2024-12-10 10:42:49,698 - INFO - 304 GET / (::1) 0.00ms
2024-12-10 10:42:49,797 - INFO - 200 GET /static/style.css (::1) 64.98ms
2024-12-10 10:42:49,815 - INFO - 200 GET /static/app.js (::1) 16.52ms
2024-12-10 10:42:52,276 - INFO - 101 GET /ws?username=%D0%A1%D0%B0%D0%BB%D0%B0%D0%BC (::1) 0.00ms
2024-12-10 10:42:52,276 - INFO - Active users updated: ['Алексей', 'Салам']
2024-12-10 10:42:52,277 - INFO - User connected: Салам
2024-12-10 10:42:52,548 - WARNING - 404 GET /favicon.ico (::1) 0.00ms
2024-12-10 10:43:03,487 - INFO - Message received from Салам: дарова заебал
2024-12-10 10:43:03,489 - INFO - Redis message received: {"type": "message", "user": "\u0421\u0430\u043b\u0430\u043c", "text": "\u0434\u0430\u0440\u043e\u0432\u0430 \u0437\u0430\u0435\u0431\u0430\u043b"}
2024-12-10 10:43:54,968 - INFO - 200 GET / (::1) 1.00ms
2024-12-10 10:43:54,995 - INFO - 200 GET /static/style.css (::1) 1.00ms
2024-12-10 10:43:55,003 - INFO - 200 GET /static/app.js (::1) 1.00ms
2024-12-10 10:43:57,590 - INFO - 101 GET /ws?username=%D0%A1%D0%B0%D0%BD%D1%8F (::1) 0.00ms
2024-12-10 10:43:57,591 - INFO - Active users updated: ['Алексей', 'Салам', 'Саня']
2024-12-10 10:43:57,591 - INFO - User connected: Саня
2024-12-10 10:43:57,624 - WARNING - 404 GET /favicon.ico (::1) 0.00ms
2024-12-10 10:44:06,264 - INFO - Message received from Саня: хуй
2024-12-10 10:44:06,266 - INFO - Redis message received: {"type": "message", "user": "\u0421\u0430\u043d\u044f", "text": "\u0445\u0443\u0439"}
2024-12-10 10:46:33,983 - INFO - 200 GET / (::1) 1.01ms
2024-12-10 10:46:33,988 - INFO - Active users updated: ['Салам', 'Саня']
2024-12-10 10:46:33,989 - INFO - User disconnected: Алексей
2024-12-10 10:46:34,060 - INFO - 200 GET /static/style.css (::1) 3.00ms
2024-12-10 10:46:34,063 - INFO - 200 GET /static/app.js (::1) 1.00ms
2024-12-10 10:46:37,432 - INFO - 101 GET /ws?username=%D0%9C%D0%B0%D1%80%D0%B0%D1%82 (::1) 1.00ms
2024-12-10 10:46:37,432 - INFO - Active users updated: ['Салам', 'Саня', 'Марат']
2024-12-10 10:46:37,434 - INFO - User connected: Марат
2024-12-10 10:47:32,466 - INFO - 200 GET / (::1) 0.00ms
2024-12-10 10:47:32,474 - INFO - Active users updated: ['Салам', 'Саня']
2024-12-10 10:47:32,475 - INFO - User disconnected: Марат
2024-12-10 10:47:32,540 - INFO - 200 GET /static/style.css (::1) 3.02ms
2024-12-10 10:47:32,544 - INFO - 200 GET /static/app.js (::1) 1.00ms
2024-12-10 10:47:33,430 - INFO - 101 GET /ws?username=1234 (::1) 1.00ms
2024-12-10 10:47:33,434 - INFO - Active users updated: ['Салам', 'Саня', '1234']
2024-12-10 10:47:33,435 - INFO - User connected: 1234
2024-12-10 10:48:42,109 - INFO - Active users updated: ['Салам', '1234']
2024-12-10 10:48:42,110 - INFO - User disconnected: Саня
2024-12-10 10:50:39,786 - INFO - 200 GET / (::1) 0.00ms
2024-12-10 10:50:39,793 - INFO - Active users updated: ['Салам']
2024-12-10 10:50:39,794 - INFO - User disconnected: 1234
2024-12-10 10:50:39,850 - INFO - 200 GET /static/style.css (::1) 2.01ms
2024-12-10 10:50:39,854 - INFO - 200 GET /static/app.js (::1) 2.00ms
2024-12-10 10:50:40,808 - INFO - 101 GET /ws?username=1234 (::1) 1.00ms
2024-12-10 10:50:40,810 - INFO - Active users updated: ['Салам', '1234']
2024-12-10 10:50:40,812 - INFO - User connected: 1234
2024-12-10 10:51:05,563 - INFO - 200 GET / (::1) 1.01ms
2024-12-10 10:51:05,568 - INFO - Active users updated: ['Салам']
2024-12-10 10:51:05,568 - INFO - User disconnected: 1234
2024-12-10 10:51:05,623 - INFO - 200 GET /static/style.css (::1) 2.00ms
2024-12-10 10:51:05,625 - INFO - 200 GET /static/app.js (::1) 1.00ms
2024-12-10 10:51:07,005 - INFO - 101 GET /ws?username=1234 (::1) 1.00ms
2024-12-10 10:51:07,006 - INFO - Active users updated: ['Салам', '1234']
2024-12-10 10:51:07,007 - INFO - User connected: 1234
2024-12-10 10:53:06,629 - INFO - 200 GET / (::1) 1.00ms
2024-12-10 10:53:06,638 - INFO - Active users updated: ['Салам']
2024-12-10 10:53:06,638 - INFO - User disconnected: 1234
2024-12-10 10:53:06,696 - INFO - 200 GET /static/style.css (::1) 2.00ms
2024-12-10 10:53:06,698 - INFO - 200 GET /static/app.js (::1) 1.00ms
2024-12-10 10:53:07,898 - INFO - 101 GET /ws?username=1234 (::1) 0.99ms
2024-12-10 10:53:07,898 - INFO - Active users updated: ['Салам', '1234']
2024-12-10 10:53:07,899 - INFO - User connected: 1234
2024-12-10 10:53:55,044 - INFO - 200 GET / (::1) 0.99ms
2024-12-10 10:53:55,049 - INFO - Active users updated: ['Салам']
2024-12-10 10:53:55,049 - INFO - User disconnected: 1234
2024-12-10 10:53:55,104 - INFO - 200 GET /static/style.css (::1) 1.00ms
2024-12-10 10:53:55,106 - INFO - 200 GET /static/app.js (::1) 1.01ms
2024-12-10 10:53:56,047 - INFO - 101 GET /ws?username=1234 (::1) 1.01ms
2024-12-10 10:53:56,047 - INFO - Active users updated: ['Салам', '1234']
2024-12-10 10:53:56,048 - INFO - User connected: 1234
2024-12-10 10:55:35,624 - INFO - 200 GET / (::1) 1.00ms
2024-12-10 10:55:35,630 - INFO - Active users updated: ['Салам']
2024-12-10 10:55:35,631 - INFO - User disconnected: 1234
2024-12-10 10:55:35,695 - INFO - 200 GET /static/style.css (::1) 3.99ms
2024-12-10 10:55:35,697 - INFO - 200 GET /static/app.js (::1) 1.00ms
2024-12-10 10:55:36,550 - INFO - 101 GET /ws?username=1234 (::1) 0.00ms
2024-12-10 10:55:36,551 - INFO - Active users updated: ['Салам', '1234']
2024-12-10 10:55:36,553 - INFO - User connected: 1234
2024-12-10 10:55:55,875 - INFO - 200 GET / (::1) 0.99ms
2024-12-10 10:55:55,881 - INFO - Active users updated: ['Салам']
2024-12-10 10:55:55,882 - INFO - User disconnected: 1234
2024-12-10 10:55:55,940 - INFO - 200 GET /static/style.css (::1) 1.01ms
2024-12-10 10:55:55,944 - INFO - 200 GET /static/app.js (::1) 3.00ms
2024-12-10 10:55:57,785 - INFO - 101 GET /ws?username=123413251325213412 (::1) 0.00ms
2024-12-10 10:55:57,786 - INFO - Active users updated: ['Салам', '123413251325213412']
2024-12-10 10:55:57,786 - INFO - User connected: 123413251325213412
2024-12-10 10:56:58,851 - INFO - 200 GET / (::1) 0.00ms
2024-12-10 10:56:58,856 - INFO - Active users updated: ['Салам']
2024-12-10 10:56:58,857 - INFO - User disconnected: 123413251325213412
2024-12-10 10:56:58,923 - INFO - 200 GET /static/style.css (::1) 3.01ms
2024-12-10 10:56:58,926 - INFO - 200 GET /static/app.js (::1) 0.99ms
2024-12-10 10:56:59,877 - INFO - 101 GET /ws?username=1234 (::1) 2.00ms
2024-12-10 10:56:59,878 - INFO - Active users updated: ['Салам', '1234']
2024-12-10 10:56:59,880 - INFO - User connected: 1234
2024-12-10 10:57:48,603 - INFO - 200 GET / (::1) 0.98ms
2024-12-10 10:57:48,607 - INFO - Active users updated: ['Салам']
2024-12-10 10:57:48,607 - INFO - User disconnected: 1234
2024-12-10 10:57:48,665 - INFO - 200 GET /static/style.css (::1) 3.00ms
2024-12-10 10:57:48,667 - INFO - 200 GET /static/app.js (::1) 1.00ms
2024-12-10 10:57:49,534 - INFO - 101 GET /ws?username=1234 (::1) 1.00ms
2024-12-10 10:57:49,535 - INFO - Active users updated: ['Салам', '1234']
2024-12-10 10:57:49,535 - INFO - User connected: 1234
2024-12-10 10:57:54,376 - INFO - 304 GET / (::1) 0.57ms
2024-12-10 10:57:54,576 - INFO - 304 GET /static/style.css (::1) 0.00ms
2024-12-10 10:57:56,969 - INFO - 101 GET /ws?username=asdgasdf (::1) 1.00ms
2024-12-10 10:57:56,969 - INFO - Active users updated: ['Салам', '1234', 'asdgasdf']
2024-12-10 10:57:56,969 - INFO - User connected: asdgasdf
2024-12-10 10:58:27,147 - INFO - 200 GET / (::1) 1.01ms
2024-12-10 10:58:27,152 - INFO - Active users updated: ['Салам', 'asdgasdf']
2024-12-10 10:58:27,152 - INFO - User disconnected: 1234
2024-12-10 10:58:27,205 - INFO - 200 GET /static/style.css (::1) 1.01ms
2024-12-10 10:58:27,208 - INFO - 200 GET /static/app.js (::1) 1.00ms
2024-12-10 10:58:27,999 - INFO - 101 GET /ws?username=1234 (::1) 0.00ms
2024-12-10 10:58:27,999 - INFO - Active users updated: ['Салам', 'asdgasdf', '1234']
2024-12-10 10:58:28,000 - INFO - User connected: 1234
2024-12-10 10:58:36,427 - INFO - Server started on port http://localhost:8888
2024-12-10 10:58:36,432 - INFO - Redis listener started
2024-12-10 10:58:39,599 - INFO - 200 GET / (::1) 3.01ms
2024-12-10 10:58:39,711 - INFO - 200 GET /static/style.css (::1) 52.30ms
2024-12-10 10:58:39,715 - INFO - 200 GET /static/app.js (::1) 1.99ms
2024-12-10 10:58:40,894 - INFO - 101 GET /ws?username=1234 (::1) 1.00ms
2024-12-10 10:58:40,894 - INFO - Active users updated: ['1234']
2024-12-10 10:58:40,895 - INFO - User connected: 1234
2024-12-10 10:58:54,795 - INFO - 200 GET / (::1) 0.00ms
2024-12-10 10:58:54,800 - INFO - Active users updated: []
2024-12-10 10:58:54,800 - INFO - User disconnected: 1234
2024-12-10 10:58:54,854 - INFO - 200 GET /static/style.css (::1) 1.00ms
2024-12-10 10:58:54,856 - INFO - 200 GET /static/app.js (::1) 1.00ms
2024-12-10 10:58:56,959 - INFO - 101 GET /ws?username=asdf (::1) 1.00ms
2024-12-10 10:58:56,959 - INFO - Active users updated: ['asdf']
2024-12-10 10:58:56,960 - INFO - User connected: asdf
2024-12-10 10:59:03,624 - INFO - 200 GET / (::1) 1.01ms
2024-12-10 10:59:03,629 - INFO - Active users updated: []
2024-12-10 10:59:03,629 - INFO - User disconnected: asdf
2024-12-10 10:59:03,690 - INFO - 200 GET /static/style.css (::1) 0.99ms
2024-12-10 10:59:03,692 - INFO - 200 GET /static/app.js (::1) 1.00ms
